version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/padal/OneDrive/Desktop/video-processing-fastapi/output_frames:/app/output_frames
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  qdrant:
    image: qdrant/qdrant:v1.12.1
    ports:
      - "6333:6333"
    volumes:
      - C:/Users/padal/OneDrive/Desktop/video-processing-fastapi/qdrant_data:/qdrant/storage

volumes:
  qdrant_data: